apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - image: lan123/rso-projekt:users
          imagePullPolicy: "Always"
          name: users-api
          ports:
            - containerPort: 8001
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: users-api
spec:
  type: LoadBalancer
  ports:
    - port: 8001
      protocol: TCP
      targetPort: server
  selector:
    app: users-api