apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - image: lan123/rso-projekt:users
          imagePullPolicy: "Always"
          name: users-api
          env:
            - name: KEYCLOAK_API
              value: https://dev.infincrypt.com/auth/
            - name: KEYCLOAK_REALM
              value: lan_faks
            - name: KEYCLOAK_CLIENT_ID
              value: rso
            - name: KEYCLOAK_REDIRECT_URL
              value: https://dev.infincrypt.com/*
            - name: KEYCLOAK_SSL_VERIFY
              value: true
            - name: KEYCLOAK_CLIENT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: kc-client-secret
                  key: KEYCLOAK_CLIENT_SECRET_KEY
            - name: KEYCLOAK_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: kc-admin-user
                  key: KEYCLOAK_ADMIN_USER
            - name: KEYCLOAK_ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: kc-admin-secret
                  key: KEYCLOAK_ADMIN_SECRET
          ports:
            - containerPort: 8001
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: users-api
spec:
  type: LoadBalancer
  ports:
    - port: 8001
      protocol: TCP
      targetPort: server
  selector:
    app: users-api